### PR TITLE
Update vehicleControlAddon.lua

### PR DESCRIPTION
**Pull request by Harag9**
The line within the elseif was commented out, this will probably break the block coding for the elseif I've commented out.

### CODE REVIEW

**Comment by Mogli12** [comment]
Hi,
The `elseif` block was there for a good reason. The vehicle should continue driving even if a dialog is open in that case. The comment below is the explanation.
Regards, Stefan

**Comment by Harag9** [comment]
> Hi,
> The `elseif` block was there for a good reason. The vehicle should continue driving even if a dialog is open in that case. The comment below is the explanation.
> Regards, Stefan

Hmm. ok when I tested it with the elseif commented out, the vehicle still slowed down, but didn't instantly stop as it was doing before. Strange.

In lua code, can you have an else if block with no code after it?

**Comment by Harag9** [comment]
HI Stefan

I've downloaded your version again and done some more testing... I've think I've worked out when it stops instantly -- IF I have the "Shuttle" Option turned on (space to change gear) then the tractor stops instantly in chat... with this turn OFF it just slows down as normal when you take your foot the pedal.

**Comment by Mogli12** [comment]
I think you do not understand it. It is wanted that VCA uses the handbrake if a dialog is visible. It was planned to disable it only for the ChatDialog. It just does not work to detect the ChatDialog. Please check https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=97&class=10204#draw161887.

**Pull request closed without merging**
